### ISSUE TITLE
Waiting for fatastic mutured verision of code

### ISSUE THREAD

**Issue by ConnorKevin** [blue-531/TALoS#2]
Issue for the initial code:

Great work! Thank you for open-sourcing this project and for your time and effort in maintaining the code. I've been studying the paper alongside the code for several days. During installation, I encountered some issues, which I’m sharing here to assist future users.

It would be greatly appreciated if the authors could consider addressing these questions and providing a more detailed installation guide with tested code. This would greatly help others in accessing and benefiting from this excellent work.

My questions and attempts：

1. PyTorch >= 1.10 is required, but the spconv1.0 requires PyTorch >= 1.0, are they conflict?  Actually, I failed to install spconv1.0 with PyTorch == 1.10.1, and finally used spconv2.0 with some dirty work.

    (For those interested, alternative versions of 'spconv' can be found here: https://github.com/traveller59/spconv)

2. I found "train_dataset" also should be loaded when testing or validation. Since it consumes a lot of memory without being used, the code could be modified for a lighter version.
  
  https://github.com/blue-531/TALoS/blob/0531ddb4c28188ab34e448a22cfa72432948b822/run_tta_test.py#L159

  https://github.com/blue-531/TALoS/blob/0531ddb4c28188ab34e448a22cfa72432948b822/builder/data_builder_test.py#L121C1-L124C72
```python
    if use_tta:
        return train_dataset_loader, val_dataset_loader, val_pt_dataset
    else:
        return train_dataset_loader, val_dataset_loader, val_pt_dataset
```

3. I occuer the  ".astype(np.int)" failure, since it deprecated in numpy>=1.20.0, but the requirments.txt needs numpy==1.23.0, I replace them all with ".astype(int)"

4. when "load_checkpint()", pay attention to the  default filename

5. pay attention to the "--talos_root" in parameters of "run_tta_XXX.py"

6. where I am stuck now is 

https://github.com/blue-531/TALoS/blob/0531ddb4c28188ab34e448a22cfa72432948b822/network/segmentator_3d_asymm_spconv_unlock.py#L253C1-L256C56

    def forward(self, x):
        shortcut = self.conv1(x)
        shortcut.features = self.act1(shortcut.features)

发生异常: ValueError
you can't set feature directly, use 'x = x.replace_feature(your_new_feature)' to generate new SparseConvTensor instead.
  File "/home/jiangt/zhuoguang/ssc_tta/TALoS/network/segmentator_3d_asymm_spconv_unlock.py", line 256, in forward
    shortcut.features = self.act1(shortcut.features)
  File "/home/jiangt/zhuoguang/ssc_tta/TALoS/network/segmentator_3d_asymm_spconv_unlock.py", line 163, in forward
    x = self.downCntx(x)
  File "/home/jiangt/zhuoguang/ssc_tta/TALoS/network/cylinder_spconv_3d_unlock.py", line 50, in forward
    spatial_features = self.cylinder_3d_spconv_seg(features_3d, coords, batch_size, extraction)  # [batch_size, 20, 256, 256, 32]
  File "/home/jiangt/zhuoguang/ssc_tta/TALoS/run_tta_test.py", line 331, in main
    pred_logit_curr = model_baseline(feat_curr, grid_curr, val_batch_size, frame_curr['grid_ind'], use_tta=False)
  File "/home/jiangt/zhuoguang/ssc_tta/TALoS/run_tta_test.py", line 709, in <module>
    main(args)
ValueError: you can't set feature directly, use 'x = x.replace_feature(your_new_feature)' to generate new SparseConvTensor instead."

I guess it may be caused by verison conflicts in the tools.

I sincerely hope the authors can help check these issues; just a few minutes of your time could save followers countless hours of frustration. Best wishes!

**Comment by blue-531** [comment]
Thank you for your interest in our work and for offering suggestions to improve this open-source project. 
Your questions 2, 4, and 5 have been resolved, and we believe this will benefit future users greatly.

Here are responses to your remaining questions:
1. This project requires using spconv 1.0. Our testing environment used PyTorch version 1.10.1 and spconv version 1.0. For installing spconv, please use the link we provided. Since spconv is highly sensitive to compatibility, the issue mentioned in question 6 is likely due to a version mismatch with spconv.
3. The issue with np.int can be resolved by using an earlier version of numpy or by modifying the code to use .astype(int) as you suggested.
