### ISSUE TITLE
A paper question

### ISSUE THREAD

**Issue by Agito555** [blue-531/TALoS#4]
Great work! I’m opening this issue to clarify a few points from your paper: In the section on TTA for scene completion, you emphasize discarding non-static objects, but in the "Extension for Semantic Perception" section, you don't mention whether non-static objects are discarded. I’d like to know if you did discard them in that context. If not, wouldn’t non-static objects introduce additional noise or interference? And if you did discard the static objects, then your TTA would only apply to static objects—does this mean that the performance for dynamic objects wouldn’t improve?

**Comment by blue-531** [comment]
Thank you for your interest and for taking the time to read the paper! 
In the "Extension for Semantic Perception" section, we did not discard non-static objects during the creation of the semantic pseudo-GT. Instead, we used prediction confidence to retain only high-confidence predictions. Furthermore, when the predictions of two different frames did not align, we conservatively assigned an ignore label (255) to prevent potential noise or interference from affecting the results. This approach allowed us to reduce the influence of non-static objects without explicitly discarding them.

**Comment by Agito555** [comment]
Thank you for your quick reply. Let me assume a scenario where there is a car at position A, so the relevant prediction would also be at position A. However, in the next frame, the car appears at a different position, B, and there is no overlap between position A and position B. If I understand correctly, you would set the car voxels at both A and B to 255. Please correct me if I’m wrong.

**Comment by blue-531** [comment]
In cases where the car shifts from position A to position B with no overlap, we would set the car voxels at both A and B to 255. Since pseudo-GT should serve as reliable guidance for the model, we adopt a conservative approach to generate it.

**Comment by Agito555** [comment]
Thanks, my question has been resolved.
