### ISSUE TITLE
Entropy?

### ISSUE THREAD

**Issue by Agito555** [blue-531/TALoS#5]
Hello, during my in-depth study of your paper, there are some details that I don't quite understand. You use entropy to measure reliability in the paper, but entropy is typically used to measure uncertainty. When a prediction has equal probabilities, its entropy is at its maximum, meaning that it is actually the least certain about its class. I suspect this might be a typo in your paper, am I correct?

**Comment by blue-531** [comment]
As you mentioned, lower entropy indeed corresponds to higher confidence (as noted in Appendix D.4). The equation in the paper appears to contain a typo. We appreciate your feedback on this matter, and a revised version is expected to be released shortly.

Thank you for your interest in our paper and for your efforts to help improve it. We truly appreciate your constructive feedback.
